language: python
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: W8dYiGd7eb1LrP8FlWPdV19U+7hFDzW87aJ93q9LH39TvIGUAeXQb3Bj8tWOCkHInBfL1G8g8r07a4KzLgxAI6PFJlv0xTjkKAJqsVrcnFy62asjLh7/ZfJq6eVe5HZO4go+tso/75nQsKz+Sb9q1529mclcRpc3VkLrykY6tgQ=
  on:
    tags: true
